services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./config:/var/www/config
      - ./sql:/var/www/sql
      - ./data:/var/www/data
      - ./var:/var/www/var
    # Если нужно, раскомментируй для live reload PHP
    # environment:
    #   PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1