services:
  php-cli:
    build:
      context: ./docker/php-cli
    environment:
      PHP_IDE_CONFIG: "serverName=b24-php-sdk-examples-11.lan"
      APP_DEBUG: 0
      BITRIX24_PHP_SDK_LOG_LEVEL: ${BITRIX24_PHP_SDK_LOG_LEVEL}
      BITRIX24_PHP_SDK_LOG_MAX_FILES_COUNT: ${BITRIX24_PHP_SDK_LOG_MAX_FILES_COUNT}
      BITRIX24_PHP_SDK_APPLICATION_CLIENT_ID: ${BITRIX24_PHP_SDK_APPLICATION_CLIENT_ID}
      BITRIX24_PHP_SDK_APPLICATION_CLIENT_SECRET: ${BITRIX24_PHP_SDK_APPLICATION_CLIENT_SECRET}
      BITRIX24_PHP_SDK_APPLICATION_SCOPE: ${BITRIX24_PHP_SDK_APPLICATION_SCOPE}
    volumes:
      - .:/var/www/html
      - ./var/logs:/var/logs
    working_dir: /var/www/html
