services:
    _defaults:
      autowire: true
      autoconfigure: false
      public: true

    App\Controller\:
      resource: '../src/Controller/*'
    App\Repository\:
      resource: '../src/Repository/*'
    App\Robots\:
      resource: '../src/Robots/*/Handler.php'

    Bitrix24\SDK\Application\Local\Repository\LocalAppAuthRepositoryInterface:
      class: Bitrix24\SDK\Application\Local\Repository\LocalAppAuthRepository
      autowire: true

    Psr\Log\LoggerInterface:
      class: App\LoggerFactory
      autowire: true