services:
    _defaults:
      autowire: true
      autoconfigure: false
      public: true

    App\LoggerFactory:
      public: true

    App\Services\:
      resource: '../src/Services/*'

    Psr\Log\LoggerInterface:
      class: App\LoggerFactory
      autowire: true
      factory: [ '@App\LoggerFactory', 'create' ]